-- Salidas de stock automáticas ligadas a Mercado Libre (Módulo 5, fase
-- "stock al 100%"). Regla de oro: nada sale de bodega sin motivo registrado.
--
-- 1) Envíos a Full: Isaac arma el envío en el CRM ("Preparado"); la bodega
--    NO se descuenta hasta que Mercado Libre confirma que lo recibió.
create table if not exists envios_full (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  fecha timestamptz not null default now(),
  bodega_id uuid references bodegas(id),
  color_etiqueta text,
  notas text,
  estado text not null default 'PREPARADO' check (estado in ('PREPARADO', 'RECIBIDO', 'CANCELADO')),
  creado_en timestamptz not null default now(),
  cerrado_en timestamptz
);

create table if not exists envios_full_lineas (
  id uuid primary key default gen_random_uuid(),
  envio_id uuid not null references envios_full(id) on delete cascade,
  sku text not null,
  nombre text not null,
  imagen_url text,
  piezas_por_caja numeric not null default 1,
  cantidad_enviada numeric not null check (cantidad_enviada > 0),
  -- lo que Mercado Libre ya confirmó recibido (se va sumando)
  cantidad_recibida numeric not null default 0,
  -- piezas que no llegaron y se dieron por perdidas/dañadas
  merma numeric not null default 0,
  resuelta boolean not null default false,
  creado_en timestamptz not null default now()
);
create index if not exists envios_full_lineas_envio_idx on envios_full_lineas(envio_id);

-- 2) Historial del stock en Full por inventario (una fila cada vez que
--    cambia): sirve para DETECTAR recepciones (el total sube) sin depender
--    de que Isaac esté viendo la pantalla.
create table if not exists mercadolibre_full_historial (
  id uuid primary key default gen_random_uuid(),
  inventory_id text not null,
  sincronizado_en timestamptz not null default now(),
  total numeric not null default 0,
  disponible numeric not null default 0
);
create index if not exists mercadolibre_full_historial_inv_idx on mercadolibre_full_historial(inventory_id, sincronizado_en desc);

-- 3) Recepciones detectadas en Full: cada aumento del total es una tarjeta
--    "¿salió de tu bodega?" hasta que Isaac decide.
create table if not exists mercadolibre_full_recepciones (
  id uuid primary key default gen_random_uuid(),
  inventory_id text not null,
  item_id text,
  variation_id bigint,
  titulo text,
  sku_crm text,
  cantidad numeric not null check (cantidad > 0),
  total_antes numeric not null default 0,
  total_despues numeric not null default 0,
  detectado_en timestamptz not null default now(),
  atendido_en timestamptz,
  decision text check (decision in ('SALIDA', 'IGNORADA')),
  envio_id uuid references envios_full(id) on delete set null,
  movimiento_stock_id uuid
);

-- 4) Ligas desde el libro de stock hacia su origen en Mercado Libre.
alter table movimientos_stock add column if not exists orden_ml_id bigint;
alter table movimientos_stock add column if not exists envio_full_id uuid references envios_full(id) on delete set null;
alter table movimientos_stock add column if not exists recepcion_full_id uuid;
create index if not exists movimientos_stock_orden_ml_idx on movimientos_stock(orden_ml_id);

-- 5) Ventas de ML que salen de la bodega de Isaac (no Full): cuándo se
--    generó su salida, y si quedó una devolución por confirmar.
alter table mercadolibre_ordenes add column if not exists salida_generada_en timestamptz;
alter table mercadolibre_ordenes add column if not exists devolucion_estado text
  check (devolucion_estado in ('POR_CONFIRMAR', 'REINGRESADA', 'MERMA'));

-- 6) Interruptor: desde qué fecha se generan salidas automáticas por ventas
--    de ML (null = apagado). Fecha de arranque = día del conteo físico.
alter table configuracion_stock add column if not exists salidas_ml_desde date;

alter table envios_full enable row level security;
alter table envios_full_lineas enable row level security;
create policy "requiere sesion envios full" on envios_full
  for all using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "requiere sesion envios full lineas" on envios_full_lineas
  for all using (auth.uid() is not null) with check (auth.uid() is not null);
-- Las tablas de ML: RLS sin políticas (solo el servidor).
alter table mercadolibre_full_historial enable row level security;
alter table mercadolibre_full_recepciones enable row level security;
